"""initial migrations

Revision ID: c823e8aff8a5
Revises: 
Create Date: 2024-10-28 12:58:34.899581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c823e8aff8a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id_payment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_payment'),
    schema='ms_payments'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments', schema='ms_payments')
    # ### end Alembic commands ###
